travis:
  secure:
    BINSTAR_TOKEN: RFrxP6O1k0UlTIaT1OTflFl394hGphkWljDclNelc+sTECIz0+5TWGtasYHQdlHG4jEe6fDV4kSYu3cA9R8bWUCXBFQ8CbnlIn7By/DSmvSURgoftpTeohye1pih1ixlnb9I2lsiGzEgdaxjuhupseIIDXuX5ib3fg1yu8bL5Mz7rm+K+nE2Ywri4E3YWpFluOqu13MpGnKp02X5a/sK+K71QBcaZkiJOcodwcH5o5dJzZWPR1zqLg6Yv4oXsjdnr0S++OAOU2HpkarlA7zon30TGu0TfZgiCmuYfcL5Rh3Yn5mnkJULy/i8XWXrEStr6LsBvX09a7082Xo9tKH+xpb8OYZqcOPmsrX77bR3+HMRXYqnMaRfO/ulCI4eN50Z7GuDZiIIMrKbJm3r+TZUBJ13tcP1ztXi25VLVcFTCEAe93RCd0P+zjtvsG4BxX2pecnXkhuaskYDPD4bZJJM00AVX0+SiJNe9YIVIoPlwFju8P8YMRNCECcVnmVlM0kCXLdBqWxtPnK1kjgi2k26Vv37RMgy9bJHV9U2fmme0rSM1wKoUhApwXdmc3ljnIARYWblo1m+Oa4Pa33rmAv2fxynCecaMNUWhMfrB/Tvai8xE5k/jn6pivffT8h2nUx8r8SgI8bkpeZkTr7RZ+XWXdQYE2t4dWJK5i3A6PoLVMQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
